let/const -> var
lavas-project/lavas-template pull request #27
Opened 2018-02-07 09:54 UTC by easonyq

Fix #26

2018-02-07 10:19 UTC, PengXing requested changes
只是将 const/let 改了不对吧，匿名函数等其他的 es6/7 的语法也都无法运行

2018-02-08 02:45 UTC, easonyq commented
是的，箭头函数改造遗漏了

2018-02-08 03:00 UTC, PengXing commented
ssr 模式下，Node.js 最低版本要求是多少？

2018-02-08 07:35 UTC, easonyq commented
Vue SSR [官方文档](https://ssr.vuejs.org/zh/basic.html) 
> 推荐使用 Node.js 版本 6+。

2018-02-08 09:08 UTC, PengXing commented
ssr 模式下，babel 编译之后的 bundle 文件也能在低版本 Node.js 环境下运行起来的吧？

2018-02-08 09:10 UTC, PengXing approved these changes
LGTM

2018-03-05 03:00 UTC, merged